-- AlterTable
ALTER TABLE "tenant_settings" ADD COLUMN     "alertOpenCashSessionMinutes" INTEGER,
ADD COLUMN     "blockDispensationIfNoStock" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "defaultDensity" TEXT NOT NULL DEFAULT 'comfortable',
ADD COLUMN     "inventoryDisplayUnit" TEXT NOT NULL DEFAULT 'g',
ADD COLUMN     "lowStockAlertEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "lowStockThresholdGrams" DECIMAL(10,3) NOT NULL DEFAULT 50,
ADD COLUMN     "notifyCashDiscrepancy" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "notifyEmergency" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "notifyHighReceivables" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "notifyHighWaste" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "notifyLowStock" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "notifyMemberBirthday" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "notifySupportActivity" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "quickWeightValuesGrams" TEXT NOT NULL DEFAULT '1,2,3,5',
ADD COLUMN     "recommendedOpeningCash" DECIMAL(10,2),
ADD COLUMN     "requireAdjustmentReason" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "requireWasteReason" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "showNegativeScaleDiff" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "showReceiptAfterSale" BOOLEAN NOT NULL DEFAULT true;
