ALTER TYPE "NotificationType" ADD VALUE 'TRIAL_EXPIRING';
ALTER TYPE "NotificationType" ADD VALUE 'INVOICE_OVERDUE';
ALTER TYPE "NotificationType" ADD VALUE 'SUSPENSION_WARNING';
ALTER TYPE "NotificationType" ADD VALUE 'PLAN_LIMIT_WARNING';
