-- AlterEnum
ALTER TYPE "InventoryMovementType" ADD VALUE IF NOT EXISTS 'WASTE';
ALTER TYPE "InventoryMovementType" ADD VALUE IF NOT EXISTS 'DAMAGED';
ALTER TYPE "InventoryMovementType" ADD VALUE IF NOT EXISTS 'SAMPLE';

-- AlterTable
ALTER TABLE "products"
  ADD COLUMN IF NOT EXISTS "barcode" TEXT,
  ADD COLUMN IF NOT EXISTS "minimumStock" DECIMAL(10,3),
  ADD COLUMN IF NOT EXISTS "idealStock" DECIMAL(10,3),
  ADD COLUMN IF NOT EXISTS "allowDecimalQuantity" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "trackStock" BOOLEAN NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE "inventory"
  ADD COLUMN IF NOT EXISTS "reservedQuantity" DECIMAL(12,3) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "lostQuantity" DECIMAL(12,3) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "totalStockIn" DECIMAL(12,3) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "totalStockOut" DECIMAL(12,3) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "lastMovementAt" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "inventory_movements"
  ADD COLUMN IF NOT EXISTS "notes" TEXT,
  ADD COLUMN IF NOT EXISTS "source" TEXT,
  ADD COLUMN IF NOT EXISTS "batchCode" TEXT,
  ADD COLUMN IF NOT EXISTS "unitCost" DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS "totalCost" DECIMAL(10,2);
