export const en = {
  nav: { features: 'Features', advantages: 'Benefits', pricing: 'Plans', faq: 'FAQ', contact: 'Contact', requestAccess: 'Request access', login: 'Sign in' },
  hero: { title: 'Manage your club from a secure, modern and centralised platform', subtitle: 'Operational control, traceability, dispensing, inventory, cash register, analytics and more. All in a private system per organisation.', cta: 'Request demo', ctaSecondary: 'View plans' },
  stats: { modules: 'Integrated modules', encryption: 'E2E Encryption', multiTenant: 'Multi-tenant', uptime: 'Availability' },
  problem: { title: 'Does this sound familiar?', subtitle: 'The most common problems in club management.', items: ['Day-to-day operational chaos', 'Hard-to-control inventory', 'Lack of dispensing traceability', 'Frequent cash-register errors', 'Information scattered across people', 'Low visibility into team activity', 'Time-consuming manual processes'] },
  solution: { title: 'One platform that centralises everything', subtitle: 'QuickPanel360 brings daily operations into a private, secure and easy-to-use system. Each organisation has its own isolated space.', highlights: [{ title: 'One system', desc: 'Dispensing, cash register, inventory, members and analytics in one place.' }, { title: 'Private and secure', desc: 'Complete isolation per organisation with encryption and audit.' }, { title: 'Ready to use', desc: 'No complex installations. Access from any device.' }] },
  showcase: {
    tabs: { chat: 'Encrypted chat', pos: 'Dispensing', dashboard: 'Dashboard', security: 'Security' },
    chat: { title: 'Encrypted internal communication', points: ['End-to-end encrypted messages (E2E)', '@user mentions with notification', 'Reactions, replies and pinned messages', 'Real-time typing indicator', 'In-conversation search'] },
    pos: { title: 'Smart dispensing point', points: ['Member selection with status verification', 'Dispensing by weight or amount', 'Scale verification with tolerance', 'Automatic bonus by member class', 'Receipt on completion'] },
    dashboard: { title: 'Full real-time control', points: ['Daily KPIs: dispensations, cash, inventory', 'Automatic alerts for required attention', 'Activity charts by period', 'Quick access to all sections', 'Instantly updated data'] },
    security: { title: 'Professional-grade security', points: ['Access via unique secure link', 'Roles and permissions per collaborator', 'Full action audit trail', 'Emergency mode with instant lockdown', 'Complete data isolation per organisation'] },
  },
  modules: { title: 'Everything you need', subtitle: 'Modules designed to cover every area of your club.', items: { dashboard: { name: 'Dashboard', desc: 'Real-time overview of club activity.' }, pos: { name: 'Dispensing point', desc: 'Record dispensations with weight and scale control.' }, cash: { name: 'Cash register', desc: 'Open, close, movements and cash reconciliation.' }, members: { name: 'Members CRM', desc: 'Member management with history, classes and benefits.' }, inventory: { name: 'Products & inventory', desc: 'Catalogue, stock, waste and movements.' }, receivables: { name: 'Pending contributions', desc: 'Track pending contributions per member.' }, thirdParty: { name: 'Third-party contributions', desc: 'Record outgoings to suppliers and services.' }, analytics: { name: 'Analytics', desc: 'Metrics by period, collaborator and product.' }, chat: { name: 'Internal chat', desc: 'Encrypted real-time communication between collaborators.' }, notifications: { name: 'Alert centre', desc: 'Automatic alerts for inventory, cash and security.' }, security: { name: 'Security', desc: 'Link-based access, emergencies and audit.' }, platform: { name: 'Platform Admin', desc: 'Centralised management of organisations for the administrator.' } } },
  advantages: { title: 'Benefits of QuickPanel360', items: [{ title: 'Operational control', desc: 'All daily information accessible from one panel.' }, { title: 'Traceability', desc: 'Every action is recorded with full audit trail.' }, { title: 'Speed', desc: 'Workflows designed for frictionless operation.' }, { title: 'Fewer errors', desc: 'Weight verification, automatic validations and alerts.' }, { title: 'Multi-user', desc: 'Roles and permissions for every team member.' }, { title: 'Responsive', desc: 'Works on mobile, tablet and desktop.' }, { title: 'Security', desc: 'Controlled access, encryption and emergency mode.' }, { title: 'Real-time information', desc: 'Dashboard, chat and alerts updated instantly.' }] },
  security: { title: 'Security that builds trust', subtitle: 'Designed with security as a priority.', items: ['Private link-based access', 'Roles and permissions per collaborator', 'Audit trail for important actions', 'Emergency mode with instant lockdown', 'Complete isolation per organisation', 'Encrypted internal communications'] },
  pricing: { title: 'Plans tailored to your club', subtitle: 'Choose the plan that best fits your team\'s needs.', monthly: '/month', annual: '/year', usersLimit: 'collaborators', productsLimit: 'products', noLimit: 'Unlimited', recommended: 'Recommended', requestPlan: 'Request this plan', modulesIncluded: 'Modules included' },
  process: { title: 'How it works', subtitle: 'Transparent and secure.', steps: [{ title: 'Request access', desc: 'Fill in the form with your club details.' }, { title: 'We review your request', desc: 'Our team verifies the information.' }, { title: 'We confirm plan and conditions', desc: 'We contact you to confirm the details.' }, { title: 'We arrange the contribution', desc: 'We coordinate the agreed contribution method.' }, { title: 'You receive your access', desc: 'We create your space and send you the credentials.' }] },
  form: { title: 'Request access', subtitle: 'Fill in the form and we will contact you to set up your access.', name: 'Contact name', email: 'Email', phone: 'Phone (optional)', company: 'Club / company name', country: 'Country', language: 'Preferred language', plan: 'Requested plan', selectPlan: 'Select a plan', users: 'Approximate number of collaborators', message: 'Message (optional)', consent: 'I agree to be contacted by the QuickPanel360 team to process my request.', submit: 'Send request', submitting: 'Sending...', success: 'Request received. Our team will review the information and contact you.', error: 'Could not send the request. Please try again.' },
  faq: { title: 'Frequently asked questions', items: [{ q: 'Can I try the system before subscribing?', a: 'Yes, you can request a personalised demo to see the system in action.' }, { q: 'How is my access activated?', a: 'After confirming your request, our team creates your space and sends you the access credentials.' }, { q: 'Is data separated by organisation?', a: 'Yes, each organisation has its own completely isolated space.' }, { q: 'Can I change my plan?', a: 'Yes, you can request a plan change at any time by contacting our team.' }, { q: 'Does it work on mobile?', a: 'Yes, the platform is responsive and works on mobile, tablet and desktop.' }, { q: 'Is there technical support?', a: 'Yes, we offer support via internal chat and email.' }, { q: 'Can I request custom modules?', a: 'We evaluate custom functionality requests on a case-by-case basis.' }] },
  footer: { description: 'Comprehensive management platform for clubs. Operational control, security and traceability in a private system.', legal: 'Legal', privacy: 'Privacy', terms: 'Terms', contact: 'Contact', languages: 'Languages', rights: '2026 QuickPanel360. All rights reserved.' },
};

